import "./globals.css";
import type { Metadata } from "next";
import { Inter, Patrick_Hand } from "next/font/google";

import { Footer } from "@/components/footer";
import { detectLanguage } from "@/app/i18n/server";
import { I18nProvider } from "@/app/i18n/i18n-context";

const inter = Inter({ subsets: ["latin"] });
const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  variable: "--font-patrick-hand",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Neige.app Montreal",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://bolt.new/static/og_default.png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: [
      {
        url: "https://bolt.new/static/og_default.png",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const lng = await detectLanguage();

  return (
    <html lang={lng}>
      <body className={`${inter.className} ${patrickHand.variable}`}>
        <I18nProvider language={lng}>
          {children}
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
