import "../globals.css";
import type { Metadata } from "next";
import { Inter, Patrick_Hand } from "next/font/google";

import { detectLanguage } from "@/app/i18n/server";
import { I18nProvider } from "@/app/i18n/i18n-context";

const inter = Inter({ subsets: ["latin"] });
const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  variable: "--font-patrick-hand",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Neige.app Montreal",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://bolt.new/static/og_default.png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: [
      {
        url: "https://bolt.new/static/og_default.png",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const lng = await detectLanguage();

  return (
    <html lang={lng}>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
        />
        <meta
          name='apple-mobile-web-app-status-bar-style'
          content='black-translucent'
        />

        {/* theme-color meta for light/dark browser UI */}
        <meta name='theme-color' content={"#111827"} />
      </head>
      <body className={`${inter.className} ${patrickHand.variable}`}>
        <I18nProvider language={lng}>{children}</I18nProvider>
      </body>
    </html>
  );
}
